name: PrismaUtils
version: '1.0-SNAPSHOT'
main: me.kermx.prismaUtils.PrismaUtils
api-version: '1.21'
description: 'Utility plugin providing various core commands'

depend: [PlaceholderAPI]
softdepend: [Towny, WorldGuard, TownyFlight, GSit]

commands:
  # ----- Workstation Interface Commands -----
  craftingtable:
    description: Opens a crafting table interface.
    usage: /craftingtable
    permission: prismautils.command.craftingtable
    aliases: [vcraft, vwb, vworkbench]

  stonecutter:
    description: Opens a stonecutter interface.
    usage: /stonecutter
    permission: prismautils.command.stonecutter
    aliases: [scut]

  anvil:
    description: Opens an anvil interface.
    usage: /anvil
    permission: prismautils.command.anvil
    aliases: [anv]

  enchantingtable:
    description: Opens an enchanting table interface.
    usage: /enchantingtable
    permission: prismautils.command.enchantingtable
    aliases: [etable]

  smithingtable:
    description: Opens a smithing table interface.
    usage: /smithingtable
    permission: prismautils.command.smithingtable
    aliases: [smith]

  grindstone:
    description: Opens a grindstone interface.
    usage: /grindstone
    permission: prismautils.command.grindstone
    aliases: [grind]

  loom:
    description: Opens a loom interface.
    usage: /loom
    permission: prismautils.command.loom

  cartographytable:
    description: Opens a cartography table interface.
    usage: /cartographytable
    permission: prismautils.command.cartographytable

  # ----- Player Utility Commands -----
  enderchest:
    description: Opens the player's ender chest.
    usage: /enderchest
    permission: prismautils.command.enderchest
    aliases: [ec, echest]

  feed:
    description: Feeds the player.
    usage: /feed
    permission: prismautils.command.feed

  heal:
    description: Heals the player.
    usage: /heal
    permission: prismautils.command.heal

  god:
    description: Toggles god mode.
    usage: /god
    permission: prismautils.command.god

  flyspeed:
    description: Sets the player's fly speed.
    usage: /flyspeed [speed]
    permission: prismautils.command.flyspeed

  extinguish:
    description: Remove fire from yourself
    usage: /extinguish
    permission: prismautils.command.extinguish
    aliases:
      - ext

  roundrotation:
    description: Rounds the player's rotation.
    usage: /roundrotation
    permission: prismautils.command.roundrotation
    aliases:
      - snapneck

  centerblock:
    description: Teleports the player to the center of the block they are standing on.
    usage: /centerblock
    permission: prismautils.command.centerblock
    aliases:
      - snaplegs
      - middle

  limits:
    description: Show block and entity limits.
    usage: /limits
    permission: prismautils.command.limits

  mail:
    description: Send, read, and manage mail messages
    usage: /mail <send|read|clear> [player] [message]
    permission: prismautils.command.mail

  playtime:
    description: View a players playtime
    usage: /playtime [player]
    permission: prismautils.command.playtime

  afk:
    description: Set yourself as afk
    usage: /afk [player]
    permission: prismautils.command.afk

  # ----- Homes Commands -----
  home:
    description: Use homes
    usage: /home [set|del|list|help] [name]
    permission: prismautils.command.home
    aliases: [homes, prismahome, h]
  sethome:
    description: Set a home
    usage: /sethome [name]
    permission: prismautils.command.sethome
    aliases: [prismasethome, seth]
  delhome:
    description: Delete a home
    usage: /delhome [name]
    permission: prismautils.command.delhome
    aliases: [prismadelhome, delh]
  adminhome:
    description: Interact with other players' homes
    usage: /adminhome <list|tp|del> <player> [home]
    permission: prismautils.command.adminhome
    aliases: [prismaadminhome]

  # ----- Other Teleport Commands -----
  back:
    description: Teleport to previous known location
    usage: /back
    permission: prismautils.command.back
  spawn:
    description: Teleport to spawn
    usage: /spawn
    permission: prismautils.command.spawn
  tp:
    description: Teleport to another player.
    usage: /tp <player>
    permission: prismautils.command.tp
    aliases: [teleport]
  tphere:
    description: Teleport another player to your location.
    usage: /tphere <player>
    permission: prismautils.command.tphere
    aliases: [teleporthere]
  tppos:
    description: Teleport to specific coordinates, optionally in a specific world.
    usage: /tppos <x> <y> <z> [world]
    permission: prismautils.command.tppos
    aliases: [teleportpos]
  tpoffline:
    description: Teleport to an offline player's last known location.
    usage: /tpoffline <player>
    permission: prismautils.command.tpo
    aliases: [teleportoffline]


  # ----- Warps Commands -----
  warp:
    description: Teleport to a saved warp point.
    usage: /warp <name>
    permission: prismautils.command.warp
    aliases: [ warps ]
  setwarp:
    description: Create a new warp point at your current location.
    usage: /setwarp <name>
    permission: prismautils.command.setwarp
  delwarp:
    description: Delete an existing warp point.
    usage: /delwarp <name>
    permission: prismautils.command.delwarp

  # ----- Teleport Request Commands -----
  tpa:
    description: Request to teleport to another player.
    usage: /tpa <player>
    permission: prismautils.command.tpa
  tpahere:
    description: Request another player to teleport to you.
    usage: /tpahere <player>
    permission: prismautils.command.tpahere
  tpaccept:
    description: Accept a teleport request.
    usage: /tpaccept
    permission: prismautils.command.tpaccept
    aliases: [tpyes]
  tpdeny:
    description: Deny a teleport request.
    usage: /tpdeny
    permission: prismautils.command.tpdeny
    aliases: [tpno]
  tpcancel:
    description: Cancel a teleport request.
    usage: /tpcancel
    permission: prismautils.command.tpcancel
    aliases: [tpacancel]
  #  ----- Fly Commands -----
  fly:
    description: Toggle flight mode
    usage: /fly [player] [on/off]
    permission: prismautils.command.fly
    aliases: [flight]
  flytime:
    description: Check your remaining temporary flight time
    usage: /flytime
    permission: prismautils.command.flytime
    aliases: [flighttime]

  tempfly:
    description: Manage temporary flight
    usage: /tempfly <player> <add/set/check> [seconds]
    permission: prismautils.command.tempfly
    aliases: [tf]

  # ----- Item Management Commands -----
  itemname:
    description: Renames the item in the player's hand.
    usage: /itemname <name>
    permission: prismautils.command.itemname

  repair:
    description: Repairs the item in the player's hand.
    usage: /repair <hand/all>
    permission: prismautils.command.repair
    aliases: [fix]

  condense:
    description: Condenses items into their block form.
    usage: /condense <item/all>
    permission: prismautils.command.condense
    aliases: [cond, smush, c]

  uncondense:
    description: Uncondenses items into their item form, from block.
    usage: /uncondense <item/all>
    permission: prismautils.command.uncondense
    aliases: [uncond, unsmush, uc]

  trash:
    description: Opens a trash interface.
    usage: /trash
    permission: prismautils.command.trash
    aliases: [bin, disposal]

  disenchant:
    description: Disenchants the item in the player's hand.
    usage: /disenchant <item>
    permission: prismautils.command.disenchant

  # ----- World/Environment Commands -----
  near:
    description: Shows nearby players.
    usage: /near [radius]
    permission: prismautils.command.near

  ptime:
    description: Sets the player's time.
    usage: /ptime [time|reset]
    permission: prismautils.command.ptime

  pweather:
    description: Sets the player's weather.
    usage: /pweather [weather|reset]
    permission: prismautils.command.pweather

  top:
    description: Teleports the player to the top.
    usage: /top
    permission: prismautils.command.top

  bottom:
    description: Teleports the player to the bottom.
    usage: /bottom
    permission: prismautils.command.bottom

  # ----- Information Commands -----
  seen:
    description: Shows the last time a player was online.
    usage: /seen <player>
    permission: prismautils.command.seen

  measure:
    description: Measures the distance between two points.
    usage: /measure pos1|pos2 [x] [y] [z]
    permission: prismautils.command.measure
    aliases: [ruler]

  lightlevel:
    description: Show spawnable blocks
    usage: /lightlevel [radius] [duration]
    permission: prismautils.command.lightlevel

  ping:
    description: Shows the player's ping.
    usage: /ping [player]
    permission: prismautils.command.ping

  # ----- Staff Commands -----

  playerhead:
    description: Gives the player a player head.
    usage: /playerhead <player>
    permission: prismautils.command.playerhead
    aliases: [skull]

  setmodeldata:
    description: Sets the model data of the item in the player's hand.
    usage: /setmodeldata <modeldata>
    permission: prismautils.command.setmodeldata

  blockinfo:
    description: Shows information about the block the player is looking at.
    usage: /blockinfo
    permission: prismautils.command.blockinfo

  entityinfo:
    description: Shows information about the entity the player is looking at.
    usage: /entityinfo
    permission: prismautils.command.entityinfo

  iteminfo:
    description: Shows information about the item in the player's hand.
    usage: /iteminfo
    permission: prismautils.command.iteminfo

  spawnmob:
    description: Spawns mobs.
    usage: /spawnmob <mob> [amount]
    permission: prismautils.command.spawnmob

  cuff:
    description: Cuffs a player.
    usage: /cuff <player>
    permission: prismautils.command.cuff

  smite:
    description: Strikes lightning at a player.
    usage: /smite <player>
    permission: prismautils.command.smite

  clearmobs:
    description: Clears mobs.
    usage: /clearmobs [flags]
    permission: prismautils.command.clearmobs

  uptime:
    description: Shows the server uptime.
    usage: /uptime
    permission: prismautils.command.uptime

  patrol:
    description: Patrol online players.
    usage: /patrol
    permission: prismautils.command.patrol

  prismautilsfeatures:
    description: List or edit the active features of PrismaUtils.
    usage: /prismautilsfeatures [list|toggle] [feature]
    permission: prismautils.command.features
    aliases:
      - pufeatures
      - pufeature
      - puf
      - prismautilsfeature

  prismautilsreload:
    description: Reloads PrismaUtils configuration.
    usage: /prismautilsreload [config]
    permission: prismautils.command.reload
    aliases:
      - pureload
      - pur

permissions:
  prismautils.keepinventory:
    description: Allows the player to keep their inventory on death.
    default: op
  prismautils.allowspawneggs:
    description: Enable the vanilla use of spawn eggs without crouch clicking.
    default: op
  prismautils.cooldown.bypass:
    description: Byass all cooldowns
    default: op
  prismautils.user.teleports:
    description: Default user permissions for prismautils
    default: true
    children:
        prismautils.command.tpa: true
        prismautils.command.tpahere: true
        prismautils.command.tpaccept: true
        prismautils.command.tpdeny: true
        prismautils.command.warp: true
        prisamutils.command.spawn: true
        prismautils.command.back: true
        prismautils.command.home: true
        prismautils.command.sethome: true
        prismautils.command.delhome: true
  prismautils.command.fly:
    description: Toggle own flight
    default: op
  prismautils.command.fly.others:
    description: Toggle flight for other players
    default: op
  prismautils.command.tempfly:
    description: Manage temporary flight
    default: op
  prismautils.fly.global:
    description: Fly anywhere
    default: op
  prismautils.fly.admin:
    description: Admin flight bypass
    default: op
  prismautils.fly.town:
    description: Fly in town plots only (excludes wilderness)
    default: false
  prismautils.fly.wilderness:
    description: Fly in wilderness only
    default: false

  # Specific plot type permissions for all valid Towny plot types
  prismautils.fly.plot.arena:
    description: Fly in arena plots
    default: false
  prismautils.fly.plot.bank:
    description: Fly in bank plots
    default: false
  prismautils.fly.plot.commercial:
    description: Fly in commercial plots
    default: false
  prismautils.fly.plot.embassy:
    description: Fly in embassy plots
    default: false
  prismautils.fly.plot.farm:
    description: Fly in farm plots
    default: false
  prismautils.fly.plot.inn:
    description: Fly in inn plots
    default: false
  prismautils.fly.plot.jail:
    description: Fly in jail plots
    default: false
  prismautils.fly.plot.residential:
    description: Fly in residential plots
    default: false
  prismautils.fly.plot.wilds:
    description: Fly in wilds plots
    default: false

#  prismautils.command.workbenches:
#    description: Allows the player to use workbench commands.
#    default: true
#    children:
#        prismautils.command.craftingtable: true
#        prismautils.command.stonecutter: true
#        prismautils.command.anvil: true
#        prismautils.command.enchantingtable: true
#        prismautils.command.smithingtable: true
#        prismautils.command.grindstone: true
#        prismautils.command.loom: true
#        prismautils.command.cartographytable: true
#        prismautils.command.enderchest: true