name: PrismaUtils
version: '1.0-SNAPSHOT'
main: me.kermx.prismaUtils.PrismaUtils
api-version: '1.21'
depend: [PlaceholderAPI]

commands:
  craftingtable:
    description: Opens a crafting table interface.
    usage: /craftingtable
    permission: prismautils.command.craftingtable
    aliases:
      - craft
      - wb
      - workbench
  stonecutter:
    description: Opens a stonecutter interface.
    usage: /stonecutter
    permission: prismautils.command.stonecutter
    aliases:
      - scut
  anvil:
    description: Opens an anvil interface.
    usage: /anvil
    permission: prismautils.command.anvil
    aliases:
      - anv
  enchantingtable:
    description: Opens an enchanting table interface.
    usage: /enchantingtable
    permission: prismautils.command.enchantingtable
    aliases:
      - etable
  smithingtable:
    description: Opens a smithing table interface.
    usage: /smithingtable
    permission: prismautils.command.smithingtable
    aliases:
      - smith
  grindstone:
    description: Opens a grindstone interface.
    usage: /grindstone
    permission: prismautils.command.grindstone
    aliases:
      - grind
  loom:
    description: Opens a loom interface.
    usage: /loom
    permission: prismautils.command.loom
    aliases:
      - loom
  cartographytable:
    description: Opens a cartography table interface.
    usage: /cartographytable
    permission: prismautils.command.cartographytable
  feed:
    description: Feeds the player.
    usage: /feed
    permission: prismautils.command.feed
  heal:
    description: Heals the player.
    usage: /heal
    permission: prismautils.command.heal
  god:
    description: Toggles god mode.
    usage: /god
    permission: prismautils.command.god
  itemname:
    description: Renames the item in the player's hand.
    usage: /itemname <name>
    permission: prismautils.command.itemname
  near:
    description: Shows nearby players.
    usage: /near [radius]
    permission: prismautils.command.near
  ptime:
    description: Sets the player's time.
    usage: /ptime <day/night>
    permission: prismautils.command.ptime
  pweather:
    description: Sets the player's weather.
    usage: /pweather <clear/rain/thunder>
    permission: prismautils.command.pweather
  repair:
    description: Repairs the item in the player's hand.
    usage: /repair <hand/all>
    permission: prismautils.command.repair
  flyspeed:
    description: Sets the player's fly speed.
    usage: /flyspeed <speed>
    permission: prismautils.command.flyspeed
  top:
    description: Teleports the player to the top.
    usage: /top
    permission: prismautils.command.top
  bottom:
    description: Teleports the player to the bottom.
    usage: /bottom
    permission: prismautils.command.bottom
  ping:
    description: Shows the player's ping.
    usage: /ping [player]
    permission: prismautils.command.ping
  setmodeldata:
    description: Sets the model data of the item in the player's hand.
    usage: /setmodeldata <modeldata>
    permission: prismautils.command.setmodeldata
  blockinfo:
    description: Shows information about the block the player is looking at.
    usage: /blockinfo
    permission: prismautils.command.blockinfo
  entityinfo:
    description: Shows information about the entity the player is looking at.
    usage: /entityinfo
    permission: prismautils.command.entityinfo
  iteminfo:
    description: Shows information about the item in the player's hand.
    usage: /iteminfo
    permission: prismautils.command.iteminfo
  prismautilsreload:
    description: Reloads PrismaUtils configuration.
    usage: /prismautilsreload
    permission: prismautils.command.reload
    aliases:
      - pureload

permissions:
  prismautils.command.workbenches:
    description: Allows the player to use workbench commands.
    default: true
    children:
        prismautils.command.craftingtable: true
        prismautils.command.stonecutter: true
        prismautils.command.anvil: true
        prismautils.command.enchantingtable: true
        prismautils.command.smithingtable: true
        prismautils.command.grindstone: true
        prismautils.command.loom: true
        prismautils.command.cartographytable: true